// Leadership & Staff Information
export const LEADERSHIP = {
  chiefMedicalOfficer: {
    name: 'Dr. Rohit Dubey',
    title: 'Chief Medical Officer & Senior Anesthesiologist',
    qualifications: 'MD (Anesthesia), FIPM',
    experience: '15+ years',
    image: '/images/doctors/dr-rohit-dubey.jpg',
    specialization: 'Anesthesiology & Critical Care',
    bio: 'Dr. Rohit Dubey leads our medical team with a vision of providing exceptional healthcare services. With over 15 years of experience in anesthesiology and critical care, he has been instrumental in establishing modern medical practices at Shriram Hospital.',
    consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    consultationTime: '10:00 AM - 2:00 PM',
    consultationFee: 500,
    email: 'rohit.dubey@shriramhospital.in',
    phone: '07652-248248'
  },
};

// Doctor Database
export const DOCTORS = [
    {
        id: 1,
        slug: 'dr-rohit-dubey',
        firstName: 'Rohit',
        lastName: 'Dubey',
        fullName: 'Dr. Rohit Dubey',
        specialization: 'Anesthesiology & Critical Care',
        departmentId: 15, // Anesthesiology & Critical Care
        qualifications: 'MD (Anesthesia), FIPM',
        experience: '15+ years',
        image: '/images/doctors/dr-rohit-dubey.jpg',
        consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        consultationTime: '10:00 AM - 2:00 PM',
        consultationFee: 500,
        isChief: true,
        isAvailable: true,
        bio: 'Highly experienced anesthesiologist with expertise in critical care medicine. Has performed over 5000+ surgeries and managed critical cases.',
        languages: ['Hindi', 'English'],
        awards: ['Best Doctor Award 2023', 'Excellence in Critical Care 2022'],
        email: 'rohit.dubey@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 2,
        slug: 'dr-sc-tripathi',
        firstName: 'S.C.',
        lastName: 'Tripathi',
        fullName: 'Dr. S.C. Tripathi',
        specialization: 'General Surgery',
        departmentId: 7, // General Surgery
        qualifications: 'MS (General Surgery)',
        experience: '20+ years',
        image: '/images/doctors/dr-sc-tripathi.jpg',
        consultationDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
        consultationTime: '9:00 AM - 1:00 PM',
        consultationFee: 400,
        isChief: false,
        isAvailable: true,
        bio: 'Senior surgeon with extensive experience in general and laparoscopic surgeries. Known for precision and patient care.',
        languages: ['Hindi', 'English'],
        awards: ['Surgical Excellence Award 2021'],
        email: 'sc.tripathi@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 3,
        slug: 'dr-sp-chaturvedi',
        firstName: 'S.P.',
        lastName: 'Chaturvedi',
        fullName: 'Dr. S.P. Chaturvedi',
        specialization: 'Obstetrics & Gynaecology',
        departmentId: 6, // Obstetrics & Gynaecology
        qualifications: 'MD (Obstetrics & Gynaecology)',
        experience: '18+ years',
        image: '/images/doctors/dr-sp-chaturvedi.png',
        consultationDays: ['Monday', 'Wednesday', 'Friday'],
        consultationTime: '10:00 AM - 2:00 PM',
        consultationFee: 450,
        isChief: false,
        isAvailable: true,
        bio: 'Senior gynecologist with a focus on comprehensive women\'s healthcare.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'sp.chaturvedi@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 4,
        slug: 'dr-geetika-shukla',
        firstName: 'Geetika',
        lastName: 'Shukla',
        fullName: 'Dr. Geetika Shukla',
        specialization: 'Obstetrics & Gynaecology',
        departmentId: 6, // Obstetrics & Gynaecology
        qualifications: 'DGO, DNB',
        experience: '10+ years',
        image: '/images/doctors/dr-geetika-shukla.jpeg',
        consultationDays: ['Tuesday', 'Thursday', 'Saturday'],
        consultationTime: '11:00 AM - 3:00 PM',
        consultationFee: 450,
        isChief: false,
        isAvailable: true,
        bio: 'Dedicated gynecologist specializing in infertility and adolescent health.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'geetika.shukla@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 5,
        slug: 'dr-amol-prabhakar-pandey',
        firstName: 'Amol Prabhakar',
        lastName: 'Pandey',
        fullName: 'Dr. Amol Prabhakar Pandey',
        specialization: 'Orthopedics',
        departmentId: 5, // Orthopedics
        qualifications: 'MS (Orthopedics)',
        experience: '12+ years',
        image: '/images/doctors/dr-amol-prabhakar-pandey.png',
        consultationDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
        consultationTime: '10:00 AM - 3:00 PM',
        consultationFee: 500,
        isChief: false,
        isAvailable: true,
        bio: 'Expert in joint replacement and trauma surgery.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'amol.pandey@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 6,
        slug: 'dr-tn-chaturvedi',
        firstName: 'T.N.',
        lastName: 'Chaturvedi',
        fullName: 'Dr. T.N. Chaturvedi',
        specialization: 'Pediatrics',
        departmentId: 13, // Pediatrics
        qualifications: 'MD (Pediatrics)',
        experience: '25+ years',
        image: '/images/doctors/dr-tn-chaturvedi.png',
        consultationDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
        consultationTime: '9:00 AM - 1:00 PM',
        consultationFee: 400,
        isChief: false,
        isAvailable: true,
        bio: 'Senior pediatrician with vast experience in neonatal and child care.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'tn.chaturvedi@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 7,
        slug: 'dr-amit-kumar-verma',
        firstName: 'Amit Kumar',
        lastName: 'Verma',
        fullName: 'Dr. Amit Kumar Verma',
        specialization: 'General Medicine',
        departmentId: 14, // General Medicine
        qualifications: 'MD (General Medicine)',
        experience: '10+ years',
        image: '/images/doctors/dr-amit-kumar-verma.png',
        consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        consultationTime: '10:00 AM - 4:00 PM',
        consultationFee: 400,
        isChief: false,
        isAvailable: true,
        bio: 'Specialist in managing chronic diseases and adult immunizations.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'amit.verma@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 8,
        slug: 'dr-amit-gaur',
        firstName: 'Amit',
        lastName: 'Gaur',
        fullName: 'Dr. Amit Gaur',
        specialization: 'Urology',
        departmentId: 8, // Urology
        qualifications: 'MS, MCh (Urology)',
        experience: '15+ years',
        image: '/images/doctors/placeholder-doctor.jpg',
        consultationDays: ['By Appointment'],
        consultationTime: 'Visiting',
        consultationFee: 700,
        isChief: false,
        isAvailable: true,
        bio: 'Visiting consultant specializing in urological surgeries and treatments.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'amit.gaur@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 9,
        slug: 'dr-aa-ansari',
        firstName: 'A.A.',
        lastName: 'Ansari',
        fullName: 'Dr. A.A. Ansari',
        specialization: 'Cardiology',
        departmentId: 1, // Cardiology
        qualifications: 'DM (Cardiology)',
        experience: '20+ years',
        image: '/images/doctors/placeholder-doctor.jpg',
        consultationDays: ['By Appointment'],
        consultationTime: 'Visiting',
        consultationFee: 800,
        isChief: false,
        isAvailable: true,
        bio: 'Visiting cardiologist with expertise in non-invasive cardiac procedures.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'aa.ansari@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 10,
        slug: 'dr-siddharth-singh',
        firstName: 'Siddharth',
        lastName: 'Singh',
        fullName: 'Dr. Siddharth Singh',
        specialization: 'Maxillofacial Surgery',
        departmentId: 16, // Maxillofacial Surgery
        qualifications: 'MDS (Maxillofacial Surgery)',
        experience: '8+ years',
        image: '/images/doctors/placeholder-doctor.jpg',
        consultationDays: ['Tuesday', 'Friday'],
        consultationTime: '2:00 PM - 5:00 PM',
        consultationFee: 500,
        isChief: false,
        isAvailable: true,
        bio: 'Expert in facial trauma, cosmetic facial surgery, and dental implants.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'siddharth.singh@shriramhospital.in',
        phone: '07652-248248'
    }
];

// Staff Categories
export const STAFF_CATEGORIES = {
  doctors: 25,
  nurses: 45,
  technicians: 30,
  administrative: 25,
  support: 25
};
