// Leadership & Staff Information
export const LEADERSHIP = {
  chiefMedicalOfficer: {
    name: 'Dr. Rohit Dubey',
    title: 'Chief Medical Officer & Senior Anesthesiologist',
    qualifications: 'MD (Anesthesia), FIPM',
    experience: '15+ years',
    image: '/images/doctors/dr-rohit-dubey.jpg',
    specialization: 'Anesthesiology & Critical Care',
    bio: 'Dr. Rohit Dubey leads our medical team with a vision of providing exceptional healthcare services. With over 15 years of experience in anesthesiology and critical care, he has been instrumental in establishing modern medical practices at Shriram Hospital.',
    consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    consultationTime: '10:00 AM - 2:00 PM',
    consultationFee: 500,
    email: 'rohit.dubey@shriramhospital.in',
    phone: '07652-248248'
  },
};

// Doctor Database
export const DOCTORS = [
    {
        id: 1,
        slug: 'dr-rohit-dubey',
        firstName: 'Rohit',
        lastName: 'Dubey',
        fullName: 'Dr. Rohit Dubey',
        specialization: 'Anesthesiology & Critical Care',
        departmentId: 15, // Anesthesiology & Critical Care
        qualifications: 'MD (Anesthesia), FIPM',
        experience: '15+ years',
        image: '/images/doctors/dr-rohit-dubey.jpg',
        consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        consultationTime: '10:00 AM - 2:00 PM',
        consultationFee: 300,
        isChief: true,
        isAvailable: true,
        bio: 'Highly experienced anesthesiologist with expertise in critical care medicine. Has performed over 5000+ surgeries and managed critical cases.',
        languages: ['Hindi', 'English'],
        awards: ['Best Doctor Award 2023', 'Excellence in Critical Care 2022'],
        email: 'rohit.dubey@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 2,
        slug: 'dr-pooja-dubey',
        firstName: 'Pooja',
        lastName: 'Dubey',
        fullName: 'Dr. Pooja Dubey',
        specialization: 'Obstetrics & Gynaecology',
        departmentId: 6, // Obstetrics & Gynaecology
        qualifications: 'MBBS, EMOC (Gynae–Obs)',
        experience: '15+ years',
        image: '/images/doctors/dr-pooja-dubey.jpg',
        consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        consultationTime: '10:00 AM - 4:00 PM',
        consultationFee: 300,
        isChief: false,
        isAvailable: true,
        isMedicalSuperintendent: true,
        bio: 'With 15 years of practice in Gynae-obstetric care and thousands of deliveries and C-sections, she is a renowned figure in Shahdol and surrounding area. She is also known for compassionate but professional care.',
        languages: ['Hindi', 'English'],
        awards: ['Excellence in Women\'s Healthcare 2023'],
        email: 'pooja.dubey@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 3,
        slug: 'dr-sc-tripathi',
        firstName: 'S.C.',
        lastName: 'Tripathi',
        fullName: 'Dr. S.C. Tripathi',
        specialization: 'General Surgery',
        departmentId: 7, // General Surgery
        qualifications: 'MS (General Surgery)',
        experience: '20+ years',
        image: '/images/doctors/dr-sc-tripathi.jpg',
        consultationDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
        consultationTime: '9:00 AM - 1:00 PM',
        consultationFee: 300,
        isChief: false,
        isAvailable: true,
        bio: 'Senior surgeon with extensive experience in general and laparoscopic surgeries. Known for precision and patient care.',
        languages: ['Hindi', 'English'],
        awards: ['Surgical Excellence Award 2021'],
        email: 'sc.tripathi@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 4,
        slug: 'dr-sp-chaturvedi',
        firstName: 'S.P.',
        lastName: 'Chaturvedi',
        fullName: 'Dr. S.P. Chaturvedi',
        specialization: 'General Medicine',
        departmentId: 10, // General Medicine
        qualifications: 'MBBS',
        experience: '18+ years',
        image: '/images/doctors/dr-sp-chaturvedi.png',
        consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        consultationTime: '10:00 AM - 2:00 PM',
        consultationFee: 300,
        isChief: false,
        isAvailable: true,
        bio: 'Senior physician with extensive experience in general medicine and patient care.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'sp.chaturvedi@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 5,
        slug: 'dr-geetika',
        firstName: 'Geetika',
        lastName: '',
        fullName: 'Dr. Geetika',
        specialization: 'Obstetrics & Gynaecology',
        departmentId: 6, // Obstetrics & Gynaecology
        qualifications: 'MS (Obs Gynae)',
        experience: '12+ years',
        image: '/images/doctors/dr-geetika.jpg',
        consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        consultationTime: '10:00 AM - 3:00 PM',
        consultationFee: 300,
        isChief: false,
        isAvailable: true,
        bio: 'Experienced gynecologist and obstetrician providing comprehensive women\'s healthcare services.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'geetika@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 6,
        slug: 'dr-amol-prabhakar-pandey',
        firstName: 'Amol Prabhakar',
        lastName: 'Pandey',
        fullName: 'Dr. Amol Prabhakar Pandey',
        specialization: 'Orthopedics',
        departmentId: 5, // Orthopedics
        qualifications: 'MS (Orthopedics)',
        experience: '12+ years',
        image: '/images/doctors/dr-amol-prabhakar-pandey.png',
        consultationDays: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
        consultationTime: '10:00 AM - 3:00 PM',
        consultationFee: 500,
        isChief: false,
        isAvailable: true,
        bio: 'Expert in joint replacement and trauma surgery with specialization in C-ARM guided minimally invasive surgeries.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'amol.pandey@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 7,
        slug: 'dr-tn-chaturvedi',
        firstName: 'T.N.',
        lastName: 'Chaturvedi',
        fullName: 'Dr. T.N. Chaturvedi',
        specialization: 'Pediatrics',
        departmentId: 9, // Pediatrics
        qualifications: 'MD (Pediatrics)',
        experience: '25+ years',
        image: '/images/doctors/dr-tn-chaturvedi.png',
        consultationDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
        consultationTime: '9:00 AM - 1:00 PM',
        consultationFee: 400,
        isChief: false,
        isAvailable: true,
        bio: 'Senior pediatrician with vast experience in neonatal and child care, NICU and PICU management.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'tn.chaturvedi@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 8,
        slug: 'dr-amit-kumar-verma',
        firstName: 'Amit Kumar',
        lastName: 'Verma',
        fullName: 'Dr. Amit Kumar Verma',
        specialization: 'General Medicine',
        departmentId: 10, // General Medicine
        qualifications: 'MD (General Medicine)',
        experience: '10+ years',
        image: '/images/doctors/dr-amit-kumar-verma.png',
        consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        consultationTime: '10:00 AM - 4:00 PM',
        consultationFee: 400,
        isChief: false,
        isAvailable: true,
        bio: 'Specialist in managing chronic diseases and adult immunizations.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'amit.verma@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 9,
        slug: 'dr-amit-gaur',
        firstName: 'Amit',
        lastName: 'Gaur',
        fullName: 'Dr. Amit Gaur',
        specialization: 'Urology',
        departmentId: 8, // Urology
        qualifications: 'MS, MCh (Urology)',
        experience: '15+ years',
        image: '/images/doctors/placeholder-doctor.jpg',
        consultationDays: ['By Appointment'],
        consultationTime: 'Visiting',
        consultationFee: 700,
        isChief: false,
        isAvailable: true,
        bio: 'Visiting consultant specializing in all endoscopic procedures, minimally invasive urological surgeries for prostate and kidney stones.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'amit.gaur@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 10,
        slug: 'dr-aa-ansari',
        firstName: 'A.A.',
        lastName: 'Ansari',
        fullName: 'Dr. A.A. Ansari',
        specialization: 'Cardiology',
        departmentId: 1, // Cardiology
        qualifications: 'DM (Cardiology)',
        experience: '20+ years',
        image: '/images/doctors/placeholder-doctor.jpg',
        consultationDays: ['By Appointment'],
        consultationTime: 'Visiting',
        consultationFee: 800,
        isChief: false,
        isAvailable: true,
        bio: 'Visiting cardiologist with expertise in non-invasive cardiac procedures.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'aa.ansari@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 11,
        slug: 'dr-siddharth-singh',
        firstName: 'Siddharth',
        lastName: 'Singh',
        fullName: 'Dr. Siddharth Singh',
        specialization: 'Maxillofacial Surgery',
        departmentId: 12, // Maxillofacial Surgery
        qualifications: 'MDS (Maxillofacial Surgery)',
        experience: '8+ years',
        image: '/images/doctors/placeholder-doctor.jpg',
        consultationDays: ['Tuesday', 'Friday'],
        consultationTime: '2:00 PM - 5:00 PM',
        consultationFee: 500,
        isChief: false,
        isAvailable: true,
        bio: 'Expert in facial trauma, cosmetic facial surgery, and dental implants.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'siddharth.singh@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 12,
        slug: 'dr-nilesh-jain',
        firstName: 'Nilesh',
        lastName: 'Jain',
        fullName: 'Dr. Nilesh Jain',
        specialization: 'General Surgery & Laparoscopic Surgery',
        departmentId: 7, // General Surgery
        qualifications: 'MS (General Surgery), Fellowship: Laparoscopic Surgery',
        experience: '7+ years',
        image: '/images/doctors/dr-nilesh-jain.jpg',
        consultationDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        consultationTime: '10:00 AM - 3:00 PM',
        consultationFee: 300,
        isChief: false,
        isAvailable: true,
        bio: 'Experienced surgeon specializing in minimally invasive laparoscopic procedures with a focus on patient care and quick recovery.',
        languages: ['Hindi', 'English'],
        awards: ['Excellence in Laparoscopic Surgery 2023'],
        email: 'nilesh.jain@shriramhospital.in',
        phone: '07652-248248'
    },
    {
        id: 13,
        slug: 'dr-aa-gaj',
        firstName: 'A.A.',
        lastName: 'Gaj',
        fullName: 'Dr. A.A. Gaj',
        specialization: 'General Surgery & Laparoscopy',
        departmentId: 7, // General Surgery
        qualifications: 'MS (General Surgery)',
        experience: '10+ years',
        image: '/images/doctors/placeholder-doctor.jpg',
        consultationDays: ['Monday', 'Wednesday', 'Friday'],
        consultationTime: '11:00 AM - 2:00 PM',
        consultationFee: 300,
        isChief: false,
        isAvailable: true,
        bio: 'Skilled general and laparoscopic surgeon providing comprehensive surgical care.',
        languages: ['Hindi', 'English'],
        awards: [],
        email: 'aa.gaj@shriramhospital.in',
        phone: '07652-248248'
    }
];

// Staff Categories
export const STAFF_CATEGORIES = {
  doctors: 25,
  nurses: 45,
  technicians: 30,
  administrative: 25,
  support: 25
};
